### ISSUE TITLE
Documentation for socket endpoints

### ISSUE THREAD

**Issue by alexklibisz** [akloster/jupyter-flightgear#1]
I'm trying to read from the fgfs websockets in a similar way to your project. I've looked around but I cannot seem to find documentation for the websocket API. Is this documented somewhere, or did you just probe to figure out how they work?

**Comment by akloster** [comment]
I believe it is undocumented, I just figured it out myself. It is normally used by FlightGear's webgui. It seems to send data at a higher rate than the documented APIs.

**Comment by alexklibisz** [comment]
@akloster Ok, thanks for the info. I'll continue to probe and use your code as a starting point.
